# Generated by Django 5.1.3 on 2026-03-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='acepta_tratamiento_datos',
            field=models.BooleanField(default=False, verbose_name='Acepta tratamiento de datos'),
        ),
    ]
