# Generated by Django 5.1.3 on 2026-03-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_gestion_qr', '0002_solicitud_acepta_tratamiento_datos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatecliente',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='templatecliente',
            name='uniq_template_por_cliente_y_nombre',
        ),
        migrations.AlterField(
            model_name='templatecliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='templatecliente',
            name='nombre',
            field=models.CharField(choices=[('crear_solicitud.html', 'Formulario de Solicitud'), ('landing_cliente.html', 'Landing Cliente')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
